apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ccc"
  description: "ccc"
  tags:
    - sx-cnp-oss
    - template
    - metalstack
  links:
    - url: https://grafana-metalstack.platform-engineer.cloud/
      title: Grafana SRE Metrics
      icon: web
  annotations:
    github.com/project-slug: phac008/ccc
    backstage.io/kubernetes-id: ccc
    kubecost.com/deployment-name: ccc
    argocd/app-name: ccc
    backstage.io/kubernetes-label-selector: app=ccc
    argocd/app-namespace: team1-ccc
    backstage.io/kubernetes-namespace: team1-ccc
    kubevirt-manager: "https://kubevirt-manager-metalstack.platform-engineer.cloud/"
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: "(tags @> 'kubevirt')"
    grafana/overview-dashboard: "https://grafana-metalstack.platform-engineer.cloud/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=&var-namespace=prod-demo-kubevirt&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: prod
  owner: "team1"
  system: ccc
  dependsOn:
    - resource:argocd
    - resource:kubevirt
    - resource:kubecost
    - resource:k8s-monitoring
    - resource:kubevirt-manager
    - resource:kubevirt
    - resource:loki
